spring.application.name=shortener
# Datenbank Verbindung
spring.datasource.url=jdbc:mysql://localhost:3306/url_shortener
spring.datasource.username=springuser
spring.datasource.password=neuespasswort123

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# optional: Dialect (meist nicht nötig)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
